let MarksOfSub1 = +prompt("enter your first subject number")
let MarksOfSub1 = +prompt("enter your first subject number")
let MarksOfSub1 = +prompt("enter your first subject number")
let MarksOfSub1 = +prompt("enter your first subject number")
let MarksOfSub1 = +prompt("enter your first subject number")
